spring:
  application:
    name: devworks-payment-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # Adds type information for deserialization
server:
  port: 8082