spring:
  application:
    name: devworks-delivery-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Allows deserializing incoming JSON events
        spring.json.value.default.type: com.devworks.event.PaymentCompletedEvent